### ISSUE TITLE
travis dando erro ao carregar firefox no karma

### ISSUE THREAD

**Issue by RicardoLuizSilveira** [ondetemjogo/frontend#9]
Quando o travis executa os testes no momento em que ele executa o karma com o firefox acontece algum problema.

[Saida do erro do TravisCI](https://travis-ci.org/ondetemjogo/frontend/builds/170964768)

**Comment by Falci** [comment]
Quando rodar teste e2e no servidor é melhor usar o [PhantomJS](http://phantomjs.org/)

**Comment by altitdb** [comment]
@Falci why PhantomJS is better? In your words of course.

**Comment by Falci** [comment]
**PRO:**
PhantomJS doesn't have a GUI. It was created to run on servers.

**CRON:**
It may have a different behavior in some cases if compared with real browsers (I read it, never happened to me)
